### PR TITLE
Simple Chat Demo addition

### PR DESCRIPTION
**Pull request by pscott-au**
* Chat client can behave stand-alone without GraphQL
* Next step - refine and add optional JS POST messages and Subscribe through /graphql
* no external JS dependencies

### CODE REVIEW

**Comment by pscott-au** [comment]
Have you had a chance yo review the modifications made?

**Comment by mohawk2** [comment]
To spell out here what we've chatted about on IRC: thank you for the nice UI for a real chat is really valuable, and important. Unfortunately, due to the point of this app being as a demo of GraphQL and Mojolicious, anything that adds non-GraphQL routes to talk directly to the Redis server is unacceptable.

For the connection and data-source logic,  what we need is JavaScript on the client side that (to spell out here what we also chatted about on IRC) utilises the same JavaScript as in the [Mojolicious GraphiQL plugin](https://metacpan.org/source/ETJ/Mojolicious-Plugin-GraphQL-0.17/lib/Mojolicious/Plugin/GraphQL.pm#L571) to use the Apollo GraphQL subscription code to talk to a compatible GraphQL server.

The plugin implements such a compatible GraphQL server. That is why the GraphiQL works.

What the JS would then need to do, to turn data events into UI changes, is to put code in something like this, from the [Apollo "hybrid connection" doc](https://github.com/apollographql/subscriptions-transport-ws#hybrid-websocket-transport):

```
apolloClient.subscribe({
  query: gql`
    subscription onNewItem {
        newItemCreated {
            id
        }
    }`,
  variables: {}
}).subscribe({
  next (data) {
    // Notify your application with the new arrived data
  }
});
```

You would change the "notify your application" bit to do direct DOM manipulation for something this simple. I am in no way asking for a React app, or anything that complex.

If this causes difficulties, I am pleased to support you!

**Comment by pscott-au** [comment]
If as you say "anything that adds non-GraphQL routes to talk directly to
the Redis server is unacceptable." then you can delete the controller code
and the first HTML page and link from the index page. These were included
to provide a reference illustrating how the GraphQL interface can be
integrated but your requirement is, I believe fully met if you remove
these. Without the controller code the 2nd page will work by talking only
with the GraphQL plugin endpoint. It does not use Apollo but this is a
feature not a bug. If you want someone to build an Apollo+React
subscription based chat client that retains the implicitly populated Redis
Graphql Schema then that is an Apollo demo not a GraphQL backend demo.
It is not so much that creating a React injected Apollo dependent example
is difficult - it's that it's not necessary to use the GraphQL engine
unless you wish to align your GraphQL implementation with a strong coupling
to Apollo. The JS code I've written does, as far as I can tell, everything
the Apollo library does in the context of the auto-created schema and
subscription chat model approach already coded in the backend.
Perhaps if you can confirm that it works without Apollo using only the
GraphQL endpoints we can then review whether there are any Gaps that
justify forcing strong coupling with Apollo for this example.

**Comment by mohawk2** [comment]
Thanks for the additional thoughts. I don't know why you keep mentioning React. I did say I'm after Apollo, and explicitly not React, just simple JS that directly manipulates the DOM, like you've got. You're aware they're different projects?

In any case, you've said I can delete things, so if I get to it before you do, I will do just that and add the Apollo JS code. Obviously, the stuff you've contributed will go in with your name, I think that's fundamental. If you _do_ get to it before me, so much the better.

Thank you for the work so far!

**Comment by pscott-au** [comment]
Not sure which of the components involved you mean to identify as different projects (Apollo/React/Mojo/Plugin) but also not sure how to address your request to use Apollo without React. 
As best I can tell the cdn included GraphQL front-end uses React as indicated looking at the files loaded 
image


I've removed the first Redis-Only version of the chat that does not use the GraphQL endpoints. I had expected this to be useful within the demo to show how to internally interface to the backend structure without GraphQL as a reference and making the GraphQL less of a black-box for people already familiar with Redis PubSub. 
I can understand the argument that his could be a distraction - so as you suggested I have removed it.

I will be interested to see whether/how you can simply "just insert the Apollo JS code". When I look at https://www.apollographql.com/client/ it suggests to me that the Apollo JS code is not intended to run stand-alone. 
When I tinkered around and followed the trail you suggested to the Apollo call embedded in the Module code it looks to me to very much require React and I was unable to get a plain version working. If you are able to do this simply I would be interested in seeing it.

If the Perl Module is actually an Apollo-JS-GraphQL module and not intended to be run without Apollo perhaps that should be more loudly stated ( ie module names / Readmes etc ). 

Anyway - I hope that the front-end pure JS version I provided can be of some use. it includes some priming GET requests that I assume set the GraphQL state that could probably be trimmed and refined to get to the 'essential' parameters but I believe that it does what I intended in providing an example of POST messages and setup a subscription Websocket to receive RedisPubSub messages through the GraphQL plugin interface.

**Comment by mohawk2** [comment]
From the Apollo client site you linked:

> The only GraphQL client that works with any client-side architecture and every GraphQL server. It adapts to fit your needs.

I expect the only reason they have lots of React in the upfront examples is because React is very fashionable. I still don't know it, and I am 100% sure that the Apollo client will be fine without it!

My rationale for wanting to use the Apollo client code is simply to not reinvent any unnecessary wheels. The wire protocol (including ignoring keepalives, which I don't think your raw code does - and without them the WS will time out pretty quickly) is fiddly (for good reasons). I had to implement the backend part of it in Perl because I had no choice. The frontend part, it doesn't make sense to not use Apollo code.

By the way, the "priming" requests you've put in are unnecessary for our purpose, so they can go. GraphiQL does them so it can auto-complete interactively for the schema you're talking to, and also provide a nice "Docs" interface.

**Comment by mohawk2** [comment]
Just to respond to your other point: I'm entirely aware that GraphiQL uses React. With the subscription stuff, it also utilises Apollo. However, while GraphiQL depends on React, Apollo does not :-)

**Comment by pscott-au** [comment]
I'm confused because I don't understand how you could build a backend that assumes a front-end protocol compatibility with a JS library without actually having any examples that use the front end library? How did you test the backend protocol handling without using Apollo?

I didn't dig too deeply into the Perl modules - but the hard coded JS snippets all seem to include React bundled and to my mind fiddling with this would result in mostly reverse engineering the usage of Apollo.

If the Apollo usage is as trivial as you seem to be suggesting then surely you could paste a working example more easily than trying to explain to me why Apollo is the answer here.

Re the quote you cite from the apollo graphql site - I also see on the home page it saying that it is "Built for modern React apps" .. "and everything else in the React ecosystem". The 'Get started' link on the homepage gives a 404 with https://www.apollographql.com/docs/react which again shows tight coupling with react. 
The comments along the lines of 'just insert into the DOM' are all indicators to me of the sort of thing that React does. Inserting a socket client into the Dom isn't something that you'd typically say for pure JS starting point - at least in my circles and my meagre JS skills.

I understand that it may well be possible to use Apollo without React but as best I could work out you can't just have an include Apollo.js and start making calls as your snippets seem to indicate. Perhaps this is possible but even if this is the case ( unable to find any examples ) then the code process would still require trying to diagnose how the Apollo is talking to the backend and where/how state is being managed etc through another couple of layers of non-perl code.

My testing indicated that the priming was required - perhaps because unable to subscribe if there is nothing in the Redis store - but I think more than that as connections without this simply don't work reliably. Again I wonder if you've run the code as if it works fine for you without the priming then that's not what I would expect. 
My sense is that the priming is involved in the referrer origins state before accepting the socket connection ( isomorphic perhaps ) but I'm not confident about this intuit.
The snippet at [https://spiffy.tech/blog/using-a-graphql-subscription-with-vanilla-js/ ](https://spiffy.tech/blog/using-a-graphql-subscription-with-vanilla-js/ )indicates that a priming GET may not be required ( though is possible the lib does it ) - in fact this snippet would probably be the next thing to play with if I was keen to dig into a non plan JS client subscription connection.

I found it useful to run "monitor" on redis-cli and also watch the socket traffic through broser dev tools using both the GraphiQL interface and the raw JS implementation which is how I came to acquire the priming GET which testing strongly suggested was required.

The keep-alives I see are sent server-side (and ignored in the JS client code) should not pose any problems during testing and serve to prevent the front end socket timing out. Perhaps you are thinking of the socket reconnect on dropout logic ( connection interruption / network outage etc) - but this isn't something that seemed to be required for a basic demo. 


If as you say "it doesn't make sense to not use Apollo code." then just delete this pull request as that's not the path I'm on here and my journey objective was originally to find an example of redis usage of pubsub and not to get deep into the Apollo implementation or use a cobbled pubsub GraphQL pubsub interface without persistence. 

Suggest if asking someone to put together a demo front end chat example you could provide them with snippets of the JS that include Apollo, establish the socket connection, send a message over that channel and establish a subscription.

I'm all for not re-inventing the wheel - but it's kinda hard to demo a new tyre by sticking it on a 18 wheeler truck and taking it for a spin. My tour of duty here is short so I'm not looking to drive the Apollo truck but perhaps someone more familiar (or willing to become familiar) with it can do this quickly and easily. 

A Few Interesting links found looking for examples of PubSub in Plain JS:

- https://stackoverflow.com/questions/45113394/how-do-i-create-a-graphql-subscription-with-apollo-client-in-vanilla-js
- https://spiffy.tech/blog/using-a-graphql-subscription-with-vanilla-js/. ** suggest that this might be the droid you are looking for **

**Comment by mohawk2** [comment]
> How did you test the backend protocol handling without using Apollo?

Using GraphiQL. Getting that working was a fair bit of work, but I wasn't going to invent my own WebSocket protocol. Plus, as discussed above, being compatible with Apollo instantly unlocks being able to use all the available JS libraries.

I've removed all the unnecessary stuff, and put the CSS in a separate template.

Next up, I'll polish the JS and put it into a separate JS template (using the DOM communicate params like the username). Then I'll experiment with the Apollo client library. Thank you for this valuable contribution, and watch this space!

**Comment by mohawk2** [comment]
All works, and using the "spiffy.tech" example was indeed the way - great research. In due course it will be a good idea to make this app actually use the full-on Apollo software, together with webpack, which is fairly straightforward.

If you want to make a chat system with persistence, that shouldn't be very hard. I think I said this on IRC, but to spell it out the way forward would be:
- switch from Mojo::Redis to Mojo::Pg
- design a chat protocol (so it'd have join and leave messages as well as chat)
- design and write a database schema, which would `notify` (i.e. publish) messages when created in the messages table
- make a GraphQL::Plugin::Convert for Mojo::Pg, that would leverage the MojoPubSub one in some fashion, possibly through federating
- make the chat client load some scrollback on connect

**Pull request merged**
